"""
Django settings for kanga project.

Generated by 'django-admin startproject' using Django 3.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

# =================================================================
#
# Work of the U.S. Department of Defense, Defense Digital Service.
# Released as open source under the MIT License.  See LICENSE file.
#
# =================================================================

import os
from distutils.util import strtobool
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = (
    os.getenv("APP_SECRET_KEY").strip()
    if len(os.getenv("APP_SECRET_KEY", "")) > 0
    else None
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = strtobool(os.getenv("APP_DEBUG", "False"))

ALLOWED_HOSTS = (
    os.getenv("ALLOWED_HOSTS", "").split(",")
    if len(os.getenv("ALLOWED_HOSTS", "")) > 0
    else []
)

# AWS

AWS_ACCESS_KEY_ID = os.getenv("AWS_ACCESS_KEY_ID", "")
AWS_SECRET_ACCESS_KEY = os.getenv("AWS_SECRET_ACCESS_KEY", "")
AWS_SESSION_TOKEN = os.getenv("AWS_SESSION_TOKEN", "")
AWS_DEFAULT_REGION = os.getenv("AWS_DEFAULT_REGION", "")
REMOTE_FIXTURES_BUCKET_NAME = os.getenv("REMOTE_FIXTURES_BUCKET_NAME", "")

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    #
    "phonenumber_field",
    #
    "kanga",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "kanga.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "kanga.wsgi.application"


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("DB_NAME", "kanga"),
        "USER": os.getenv("DB_USER", "kanga"),
        "PASSWORD": os.getenv("DB_PASSWORD", "kanga"),
        "HOST": os.getenv("DB_HOST", "localhost"),
        "PORT": int(os.getenv("DB_PORT", "5432")),
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = os.getenv("STATIC_ROOT", "")

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

#
# Log Settings
#

LOG_ENCODING = os.getenv("LOG_ENCODING", "console")
LOG_TIMEZONE = os.getenv("LOG_TIMEZONE", "America/New_York")
LOG_MESSAGE_WIDTH = int(os.getenv("LOG_MESSAGE_WIDTH", "60"))

#
# TLS Security
#

SESSION_COOKIE_SECURE = strtobool(os.getenv("SESSION_COOKIE_SECURE", "False"))

CSRF_COOKIE_SECURE = strtobool(os.getenv("CSRF_COOKIE_SECURE", "False"))

SESSION_EXPIRE_AT_BROWSER_CLOSE = True

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

#
# Twilio
#

TWILIO_EDGE = os.getenv("TWILIO_EDGE", "ashburn")

#
# Kanga
#

TITLE = os.getenv("APP_TITLE")

LOGIN_URL = "/admin/login/"

LOGIN_REDIRECT_URL = "/"

ASSETS_DIRECTORY = "assets"

AVAILABLE_PLATFORMS = [
    {"id": "sms", "title": "SMS/MMS"},
    {"id": "whatsapp", "title": "WhatsApp"},
]
