#!/bin/bash

set -euo pipefail

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
readonly DIR

usage() {
  echo "${0##*/} <name>"
  exit 1
}

if [[ "$#" -ne 1 ]]; then
  usage
fi

name=$1

docker stop ${name}
