#!/bin/bash

set -euo pipefail

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
readonly DIR

usage() {
  echo "${0##*/} <image> <name>"
  exit 1
}

if [[ "$#" -ne 2 ]]; then
  usage
fi

image=$1
name=$2

if ! docker start ${name} > /dev/null 2>&1; then
  docker run -d --name ${name} \
  -e POSTGRES_PASSWORD=${DB_PASSWORD} \
  -e POSTGRES_USER=${DB_USER} \
  -e POSTGRES_DB=${DB_NAME} \
  -p ${DB_PORT}:${DB_PORT} \
  ${image} \
  -c "log_statement=all"
fi
